---
# tasks file for roles/mysql

- name: Ensure python3 packages are installed on host
  apt:
    update_cache: yes
    state: present
    name: 
      - python3-dev
      - python3-pip

- name: ensure docker-py is absent
  pip:
    executable: pip3
    name: docker-py
    state: absent

- name: ensure docker for pip3 is present
  pip:
    executable: pip3
    name: docker
    state: present
    extra_args: --system

- name: "mariadb container {{ item.name }}"
  docker_container:
    name: "wp-mariadb-{{ item.name }}"
    image: mariadb
    state: started
    ports:
    - 3306
    volumes:
      - "/var/lib/mysql_{{ item.name }}:/var/lib/mysql"
    env:
      MYSQL_DATABASE: "{{ item.name }}"
      MYSQL_USER: "{{ item.db_user }}"
      MYSQL_PASSWORD: "{{ item.db_password }}"
      MYSQL_ROOT_PASSWORD: "{{ item.db_root_password}}"
    restart_policy: always
  with_items: "{{ wordpress_stacks }}"

- name: wp container
  docker_container:
    name: "wp-app-{{ item.name }}"
    image: wordpress
    state: started
    ports: "{{ item.expose_port }}:80"
    links:
      - "wp-mariadb-{{ item.name }}:mysql"
    volumes:
    - "/var/lib/wordpress_{{ item.name }}:/var/www/html"
    env:
      WORDPRESS_DB_HOST: "wp-mariadb-{{ item.name }}:3306"
      WORDPRESS_DB_USER: "{{ item.db_user }}"
      WORDPRESS_DB_PASSWORD: "{{ item.db_password }}"
      WORDPRESS_DB_NAME: "{{ item.name }}"
    restart_policy: always
  with_items: "{{ wordpress_stacks }}"
